### ISSUE TITLE
Suspected dependency on HIT beamer theme

### ISSUE THREAD

**Issue by LuciaZhang9** [YangLaTeX/thubeamer#1]
Thank you for sharing this amazing work! well however there seems to be a weird dependency on HIT's theme...which nonetheless doesn't affect installing IF the corresponding 'hitszbeamer.dtx' is paste into the folder

Output when trying "make doc" in terminal(macOS):

`thubeamer % make doc
xelatex hitszbeamer.dtx
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file 'hitszbeamer.dtx'.
<*> hitszbeamer.dtx `

**Comment by jingxuanyang** [comment]
Thanks for pointing out this problem. The package uploaded to CTAN has this problem, which was corrected in this repo. Please kindly use the `Makefile` provided here.

**Comment by YangLaTeX** [comment]
Hello, the weird dependency on HIT's theme is a bug in `Makefile`. I forgot to correct it when modifying that file from `hitszbeamer` package. When I noticed this bug, this package was already uploaded to CTAN. I'll upload a new version of this template soon to CTAN concerning two issues.
