### ISSUE TITLE
make `ctex` optional to support English presentation and speed up compilation

### ISSUE THREAD

**Issue by zhaofeng-shu33** [YangLaTeX/thubeamer#2]
Loading `ctex` in the template will make `\today` command render in Chinese characters, which is not desired when
making English presentations. Besides, it needs more time to compile a Chinese template. I suggest removing the hard requirement
of dependency on `ctex`.

**Comment by YangLaTeX** [comment]
Thanks for your advise. A new option `en` is added for preparing beamer in English and an example file `main-en.tex` is provided as an example. Please kindly use version 1.1.0 of this template.

**Comment by zhaofeng-shu33** [comment]
I will try the new version the next time I made a slide.
