### ISSUE TITLE
三线表中不应该使用竖线 |

### ISSUE THREAD

**Issue by syvshc** [YangLaTeX/thubeamer#3]
https://github.com/YangLaTeX/thubeamer/blob/28ee38f0d9df3cb396e5fbd49710513ef79cef2e/thubeamer.dtx#L235-L254

根据 [booktabs 的文档](http://mirrors.ctan.org/macros/latex/contrib/booktabs/booktabs.pdf) 

![image](https://user-images.githubusercontent.com/38098591/142564437-41076e1f-239c-4d83-a81c-22b79f169df1.png)

应该避免在三线表中使用竖线

**Comment by YangLaTeX** [comment]
Thanks. I have omitted the vertical rule in documentation.
